server:
  port: 8080
spring:
  application:
    name: api
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:api;DB_CLOSE_ON_EXIT=FALSE
    username: teste
    password: 123987
  jpa:
    show-sql: true
